# Generated by Django 5.0.4 on 2024-04-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0003_assessment_question_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.CharField(max_length=10000),
        ),
    ]
