# Generated by Django 5.0.4 on 2024-08-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0005_question_input_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="submission_text",
        ),
        migrations.AddField(
            model_name="submission",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="code_path",
            field=models.CharField(default="uploads/code/1-1.py", max_length=10000),
            preserve_default=False,
        ),
    ]
