# Generated by Django 5.0.4 on 2024-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waizcode", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="content",
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(default="--", max_length=200),
            preserve_default=False,
        ),
    ]
